name: action-issue-dedup
description: Action Deduplication
inputs:
  issue:
    description: Issue number to deduplicate actions for
    required: false
    default: 2
  github_token:
    description: "GitHub token with `models: read` permission at least."
    required: true
  debug:
    description: Enable debug logging.
    required: false
    default: "*"
outputs:
  text:
    description: The generated text output.
  data:
    description: The generated JSON data output, parsed and stringified.
branding:
  icon: copy
  color: blue
runs:
  using: docker
  image: Dockerfile
