name: GenAI Issue Deduplicator
description: GitHub Action Deduplication
inputs:
  count:
    description: Number of issues to check for duplicates
    required: false
    default: 30
  since:
    description: Only check issues created after this date (ISO 8601 format)
    required: false
  labels:
    description: List of labels to filter issues by
    required: false
  state:
    description: State of the issues to check (open, closed, all)
    required: false
    default: open
  max_duplicates:
    description: Maximum number of duplicates to check for
    required: false
    default: 3
  tokens_per_issue:
    description: Number of tokens to use for each issue when checking for duplicates
    required: false
    default: 1000
  confirm_duplicates:
    description: Confirm duplicates with a large model before labeling
    required: false
    default: true
  label_as_duplicate:
    description: Apply duplicate label to the issue if duplicates are found
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: true
  github_issue:
    description: GitHub issue number to use when generating comments.
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
branding:
  icon: copy
  color: yellow
runs:
  using: docker
  image: Dockerfile
outputs:
  text:
    description: The generated text output.
