name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
  issues: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm test
  test-action:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue: 2
          count: 10
          since: '2023-01-01T00:00:00Z'
          labels: 'bug,enhancement'
          state: open
          max_duplicates: 3
          tokens_per_issue: 500
          label_as_duplicate: true
