name: GenAI Find Duplicate Issues
on:
  workflow_dispatch:
    inputs:
      issue_number:
        type: number
        description: 'Issue number to process'
        required: false
  issues:
    types: [opened, edited]
permissions:
  models: read
  issues: write
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  genai-issue-dedup:
    runs-on: ubuntu-latest
    steps:
      - name: Run action-issue-dedup Action
        uses: pelikhan/action-genai-issue-dedup@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue: ${{ github.event.inputs.issue_number || github.event.issue.number }}
          debug: "script*"
