name: Run action-issue-dedup Action
on:
  issues:
    types: [opened, edited]
permissions:
  contents: read
  models: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run action-issue-dedup Action
        uses: pelikhan/action-genai-issue-dedup@v0
        with:
          issue: ${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
